### ISSUE TITLE
Ability to choose serial parity

### ISSUE THREAD

**Issue by jeanfabrice** [syberalexis/linky-exporter#1]
Thanks a lot for this perfect exporter!

Would you mind adding a parameter to allow op to choose serial parity? I first tried the linky-exporter as-is and didn't get anything usable. Switching to serial.parityEven solved the issue.

Fyi, I'm using such kind of device : <https://www.planete-domotique.com/compteur-teleinformation-usb-rail-din.html> which require an even parity. I'm not enough qualified in Golang to submit a PR :/

**Comment by syberalexis** [comment]
Thanks to your interest to this project.
I make a PR to fix this issue ;)

**Comment by syberalexis** [comment]
I try a version.
Can you try with your hardware and tell me if it's good to you ?

**Comment by jeanfabrice** [comment]
Thanks.

Running a few test : 
* ``--parity=ParityEven`` or ``--parity="ParityEven"``: NOT OK
* ``--parity=E`` or ``--parity="E"`` OK

**Comment by syberalexis** [comment]
Sorry, i fail my switch case...
I fix it, you can now use ParityEven ;)

**Comment by jeanfabrice** [comment]
thanks!
