### ISSUE TITLE
Wrong error "Serial port busy"

### ISSUE THREAD

**Issue by dorianboulch** [syberalexis/linky-exporter#13]
Hello,
To begin, thanks a lot for your exporter, it's very usefull for myself !

When using `--standard` flag, I get this output :  
```
level=error msg="Failed to read standard serial : Serial port busy"
level=error msg="Unable to read telemetry information : Serial port busy"
```

When using `--historical` flag, there is no problem.  

Is there a problem with my configuration or my Linky isn't able to send "all standard" telemetries and the error message is wrong ?

**Comment by syberalexis** [comment]
Hello,

Linky has two TIC mode : historical or standard.
You probably are in historical TIC mode.
You can see it by clicking on the + button to switch menus on your Linky. One menu show you the actuel TIC mode.

If you want to switch in standard mode, you need to request it at your electrical provider.

You can try the automatic mode with debug : `—auto —debug`
This mode try the two modes. And the debug to see more details ;)

Have a nice day.
Best regards,
