### ISSUE TITLE
Docker Hub image

### ISSUE THREAD

**Issue by jeanfabrice** [syberalexis/linky-exporter#5]
Hello,
Would you mind setting up an automatic build workflow on docker hub so that a docker image is automatically built as you update your code?
Let me know if some help is needed.

**Comment by syberalexis** [comment]
Hello,
I try it today ;)

**Comment by jeanfabrice** [comment]
Thanks !
Btw, I can't find any tagged images syberalexis/linky-exporter. Are you sure something get pushed on the Docker Hub? Or am I missing something? Would be nice to have both `latest` (for 'master') and git tags applied to the docker image

**Comment by syberalexis** [comment]
It's done just now !
Sorry, I had some difficult to set DOCKER_USERNAME and DOCKER_PASSWORD travis' env variable...
I don't know why but it's done and i fixed and optimized the Makefile ;)
