### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by zethis** [syberalexis/linky-exporter#8]
Hey,
Thanks for your work, did you have or plan to have a Grafana dashboard ?

Thanks

**Comment by syberalexis** [comment]
Hello,
Thanks to use this project :)

I started a dashboard, i will try to make it more readable and add into the project. ;)

Have a nice day.

**Comment by syberalexis** [comment]
Hello,

The new released version of Linky exporter is ready : https://github.com/syberalexis/linky-exporter/releases/tag/v3.0.0 ;)

A dashboard is available with id 17649.
The link https://grafana.com/grafana/dashboards/17649-fr-linky-exporter/ is buggy. I opened a ticket in GrafanaLabs.

Have a nice day.
Best regards,

**Comment by zethis** [comment]
Hey, thanks again for your work ! 
I tried the exporter & the dashboard, but the metrics not matching the one in the dashboard, can you provide the rewrite rules ? thanks :)

**Comment by syberalexis** [comment]
Hello,

Do you try the dashboard with the new version of exporter ?

Have a nice week-end.

**Comment by zethis** [comment]
Ok issue fixed, tried to connect with auto detect mode but not working at the end :)
```
./linky-exporter-3.0.0-linux-armv7 -d /dev/ttyAMA0 --debug
INFO[0000] Debug mode enabled !
INFO[0000] Trying to auto detect TIC mode...
DEBU[0000] Read serial data...
DEBU[0014] Try line 1/5 :
DEBU[0014] Regex not match
DEBU[0029] Try line 2/5 :
DEBU[0029] Regex not match
DEBU[0044] Try line 3/5 :
DEBU[0044] Regex not match
DEBU[0058] Try line 4/5 :
DEBU[0058] Regex not match
DEBU[0073] Try line 5/5 :
DEBU[0073] Regex not match
DEBU[0073] It's not standard mode !
DEBU[0073] It's not historical mode !
DEBU[0073] device:/dev/ttyAMA0 mode:{0 0 0 0} baudrate:0 framesize:0 parity:0 stopbits:0
FATA[0073] Impossible to auto detect TIC mode !
```

This is the working one:
```bash
./linky-exporter-3.0.0-linux-armv7 --historical -d /dev/ttyAMA0 --debug --parity=E --baud=1200
```

Thanks again :)
